# Все константы для приложения recipes
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_TAG_SLUG = 32
REGEXP_SLUG = r'^[-a-zA-Z0-9_]+$'
MAX_LENGTH_INGRIDIENT_NAME = 128
MAX_LENGTH_MEASURMENT_UNIT = 64
MAX_LENGTH_RECIPE_NAME = 256
MIN_COOKING_TIME_MINUTES = 1
MIN_AMOUNT_OF_INGREDIENT = 1
# Для кастомной пагинации:
MAX_PAGE_SIZE = 20
PAGE_SIZE = 5
LIMIT = 'limit'
