# Все константы для приложения users
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
REGEXP_USERNAME = r'^[\w.@+-]+\Z'
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
FORBIDDEN_NAME = 'me'
MAX_FILE_SIZE_AVATAR = 5
