# Generated by Django 4.2.16 on 2024-09-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Название рецепта: обязательное поле', max_length=256, verbose_name='Название рецепта'),
        ),
    ]
