# Generated by Django 4.2.16 on 2024-09-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url_code',
            field=models.CharField(default='qwe', editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
