# Generated by Django 4.2.16 on 2024-09-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_short_url_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='user_recipe_fav_pair_unique',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='user_recipe_cart_pair_unique',
        ),
    ]
