# Generated by Django 4.2.16 on 2024-10-02 10:55

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username_follow_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='email_username_unique_pair_unique',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Имя пользователя: обязательное поле', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Юзернейм'),
        ),
    ]
